// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWHebFDX68-XfD9--IuCiemjEcwjSWb8',
    appId: '1:647168492493:web:749cef8ca41f912dfcfa84',
    messagingSenderId: '647168492493',
    projectId: 'send-email-f2206',
    authDomain: 'send-email-f2206.firebaseapp.com',
    storageBucket: 'send-email-f2206.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs383bb6k6nLTAuZ0fsJI2umq0GcYOeZM',
    appId: '1:647168492493:android:079b061f1855c566fcfa84',
    messagingSenderId: '647168492493',
    projectId: 'send-email-f2206',
    storageBucket: 'send-email-f2206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdAWEYxIZCNNY48V5DGe2viQbfiiuy_A',
    appId: '1:647168492493:ios:689e5f3c3f805a5cfcfa84',
    messagingSenderId: '647168492493',
    projectId: 'send-email-f2206',
    storageBucket: 'send-email-f2206.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdAWEYxIZCNNY48V5DGe2viQbfiiuy_A',
    appId: '1:647168492493:ios:689e5f3c3f805a5cfcfa84',
    messagingSenderId: '647168492493',
    projectId: 'send-email-f2206',
    storageBucket: 'send-email-f2206.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtWHebFDX68-XfD9--IuCiemjEcwjSWb8',
    appId: '1:647168492493:web:48eaa1279112abcffcfa84',
    messagingSenderId: '647168492493',
    projectId: 'send-email-f2206',
    authDomain: 'send-email-f2206.firebaseapp.com',
    storageBucket: 'send-email-f2206.firebasestorage.app',
  );
}
